items:
    -
        Rock:
            BetterThan:
                - Scissors
    -
        Scissors:
            BetterThan:
                - Paper
    -
        Paper:
            BetterThan:
                - Rock